import type {
  IntrospectedArgument,
  IntrospectedCommand,
  IntrospectedOption,
} from "./introspect.js"
import { inferOptionCompletionHint } from "./introspect.js"

// ── Zsh completion script generator ──────────────────────────────────
//
// Emits a standalone #compdef script that uses zsh's _arguments system.
// The generated script handles:
//   - Top-level commands with descriptions
//   - Subcommand groups (cluster, generate)
//   - Option flags with choices, file completions, and descriptions
//   - Positional arguments with file-type hints
//   - Command aliases (e.g. generate/g)

export function generateZshCompletion(tree: IntrospectedCommand): string {
  const lines: string[] = []
  const programName = tree.name

  lines.push(`#compdef ${programName}`)
  lines.push("")
  lines.push(
    "# ── Auto-generated by: flink-reactor completion zsh ─────────────",
  )
  lines.push("# Install:")
  lines.push(
    `#   ${programName} completion zsh > ~/.zsh/completions/_${programName}`,
  )
  lines.push(`#   eval "$(${programName} completion zsh)"`)
  lines.push("")

  // Main dispatcher
  lines.push(`_${ident(programName)}() {`)
  lines.push("  local -a commands")
  lines.push('  local curcontext="$curcontext" state line')
  lines.push("  typeset -A opt_args")
  lines.push("")

  // Global options
  const globalOpts = formatOptions(tree.options)
  lines.push("  _arguments -C \\")
  for (const opt of globalOpts) {
    lines.push(`    ${opt} \\`)
  }
  lines.push("    '1:command:->command' \\")
  lines.push("    '*::args:->args'")
  lines.push("")

  // Command list
  lines.push("  case $state in")
  lines.push("    command)")
  lines.push("      commands=(")
  for (const cmd of tree.subcommands) {
    const desc = escapeZsh(cmd.description)
    lines.push(`        '${cmd.name}:${desc}'`)
    for (const alias of cmd.aliases) {
      lines.push(`        '${alias}:${desc}'`)
    }
  }
  lines.push("      )")
  lines.push("      _describe 'command' commands")
  lines.push("      ;;")

  // Dispatch to subcommand handlers
  lines.push("    args)")
  lines.push("      case $line[1] in")
  for (const cmd of tree.subcommands) {
    const names = [cmd.name, ...cmd.aliases]
    lines.push(`        ${names.join("|")})`)
    lines.push(`          _${ident(programName)}_${ident(cmd.name)}`)
    lines.push("          ;;")
  }
  lines.push("      esac")
  lines.push("      ;;")

  lines.push("  esac")
  lines.push("}")
  lines.push("")

  // Generate handlers for each subcommand
  for (const cmd of tree.subcommands) {
    generateCommandHandler(lines, programName, cmd)
  }

  // Entry point
  lines.push(`_${ident(programName)} "$@"`)

  return lines.join("\n")
}

// ── Command handler generation ───────────────────────────────────────

function generateCommandHandler(
  lines: string[],
  programName: string,
  cmd: IntrospectedCommand,
): void {
  const fnName = `_${ident(programName)}_${ident(cmd.name)}`

  if (cmd.subcommands.length > 0) {
    // Subcommand group (e.g. cluster, generate)
    generateSubcommandGroup(lines, programName, cmd, fnName)
  } else {
    // Leaf command
    generateLeafCommand(lines, cmd, fnName)
  }
}

function generateSubcommandGroup(
  lines: string[],
  programName: string,
  cmd: IntrospectedCommand,
  fnName: string,
): void {
  lines.push(`${fnName}() {`)
  lines.push("  local -a subcommands")
  lines.push('  local curcontext="$curcontext" state line')
  lines.push("  typeset -A opt_args")
  lines.push("")

  const parentOpts = formatOptions(cmd.options)
  lines.push("  _arguments -C \\")
  for (const opt of parentOpts) {
    lines.push(`    ${opt} \\`)
  }
  lines.push("    '1:subcommand:->subcommand' \\")
  lines.push("    '*::args:->args'")
  lines.push("")

  lines.push("  case $state in")
  lines.push("    subcommand)")
  lines.push("      subcommands=(")
  for (const sub of cmd.subcommands) {
    const desc = escapeZsh(sub.description)
    lines.push(`        '${sub.name}:${desc}'`)
  }
  lines.push("      )")
  lines.push("      _describe 'subcommand' subcommands")
  lines.push("      ;;")

  lines.push("    args)")
  lines.push("      case $line[1] in")
  for (const sub of cmd.subcommands) {
    lines.push(`        ${sub.name})`)
    lines.push(
      `          _${ident(programName)}_${ident(cmd.name)}_${ident(sub.name)}`,
    )
    lines.push("          ;;")
  }
  lines.push("      esac")
  lines.push("      ;;")

  lines.push("  esac")
  lines.push("}")
  lines.push("")

  // Generate handlers for each subcommand's subcommands
  for (const sub of cmd.subcommands) {
    const subFnName = `_${ident(programName)}_${ident(cmd.name)}_${ident(sub.name)}`
    generateLeafCommand(lines, sub, subFnName)
  }
}

function generateLeafCommand(
  lines: string[],
  cmd: IntrospectedCommand,
  fnName: string,
): void {
  lines.push(`${fnName}() {`)

  const opts = formatOptions(cmd.options)
  const argSpecs = formatArguments(cmd.args)

  if (opts.length === 0 && argSpecs.length === 0) {
    lines.push("  _message 'no more arguments'")
  } else {
    lines.push("  _arguments \\")
    for (const opt of opts) {
      lines.push(`    ${opt} \\`)
    }
    for (let i = 0; i < argSpecs.length; i++) {
      const trailing = i < argSpecs.length - 1 ? " \\" : ""
      lines.push(`    ${argSpecs[i]}${trailing}`)
    }
    // If we only had opts, the trailing backslash needs cleanup
    if (argSpecs.length === 0 && opts.length > 0) {
      // Remove trailing backslash from last opt line
      const lastIdx = lines.length - 1
      lines[lastIdx] = lines[lastIdx].replace(/ \\$/, "")
    }
  }

  lines.push("}")
  lines.push("")
}

// ── Option formatting ────────────────────────────────────────────────

function formatOptions(options: IntrospectedOption[]): string[] {
  const specs: string[] = []

  for (const opt of options) {
    // Skip version — zsh handles it via _arguments -V pattern or we include it
    const desc = escapeZsh(opt.description)

    if (opt.isNegated) {
      // Negated options like --no-git — opt.long already includes "no-" prefix
      specs.push(`'--${opt.long}[${desc}]'`)
      continue
    }

    let valueSpec = ""
    if (opt.expectsValue) {
      if (opt.choices) {
        const choiceStr = opt.choices.join(" ")
        valueSpec = `: :(${choiceStr})`
      } else {
        // Check for file/directory hints
        const hint = inferOptionCompletionHint(`--${opt.long}`, opt.description)
        switch (hint) {
          case "directory":
            valueSpec = ": :_files -/"
            break
          case "file":
            valueSpec = ": :_files"
            break
          default:
            valueSpec = ": : "
            break
        }
      }
    }

    if (opt.short) {
      // Option with both short and long form
      specs.push(
        `'(-${opt.short} --${opt.long})'{-${opt.short},--${opt.long}}'[${desc}]${valueSpec}'`,
      )
    } else {
      specs.push(`'--${opt.long}[${desc}]${valueSpec}'`)
    }
  }

  return specs
}

// ── Argument formatting ──────────────────────────────────────────────

function formatArguments(args: IntrospectedArgument[]): string[] {
  const specs: string[] = []

  for (let i = 0; i < args.length; i++) {
    const arg = args[i]
    const desc = escapeZsh(arg.description)
    const pos = i + 1
    const optionalMark = arg.required ? "" : ":"

    let completion: string
    switch (arg.completionHint) {
      case "sql-file":
        completion = '_files -g "*.sql"'
        break
      case "tsx-file":
        completion = '_files -g "*.tsx"'
        break
      case "directory":
        completion = "_files -/"
        break
      case "file":
        completion = "_files"
        break
      default:
        completion = " "
        break
    }

    // Zsh positional: '1:description:action' (required) or '1::description:action' (optional)
    specs.push(`'${pos}${optionalMark}:${desc}:${completion}'`)
  }

  return specs
}

// ── Helpers ──────────────────────────────────────────────────────────

function ident(name: string): string {
  return name.replace(/-/g, "_")
}

function escapeZsh(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "'\\''")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/:/g, "\\:")
}
