#!/usr/bin/env tsx
/**
 * Generates a PostgreSQL-compatible TPC-H seed dump using DuckDB's
 * tpch extension, writing to `src/cli/cluster/init/tpch.sql`.
 *
 * The dump is consumed by:
 *   • Docker lane: `00-init-databases.sh` runs psql -f tpch.sql at first
 *     boot of the bundled timescaledb container.
 *   • Minikube lane: `Dockerfile.pg-init` COPYs tpch.sql into /data/, the
 *     pg-init Job's `pg-seed.sh` then loads it.
 *
 * Usage:
 *   pnpm tpch:gen                    # SF=0.01 (default — keeps repo lean)
 *   TPCH_SF=0.1 pnpm tpch:gen        # full proposal scale
 *   TPCH_SF=0.001 pnpm tpch:gen      # tiny — useful for CI snapshots
 *   TPCH_SF=10 pnpm tpch:gen         # 15M orders local (gitignored, gzipped)
 *
 * Output behaviour:
 *   • SF < 1   → writes uncompressed `tpch.sql`. The committed default
 *     (SF=0.01, ~10MB) lives here.
 *   • SF >= 1  → writes gzipped `tpch.sql.gz`. The init script prefers
 *     .gz when present; any stale large `tpch.sql` is cleaned up but the
 *     small committed SF=0.01 dump is preserved.
 *
 * Requirements:
 *   • DuckDB CLI on PATH (brew install duckdb)
 *   • The tpch extension auto-installs on first invocation.
 */

import { execSync } from "node:child_process"
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { gzipSync } from "node:zlib"

const SF = Number.parseFloat(process.env.TPCH_SF ?? "0.01")
const REPO_ROOT = join(import.meta.dirname, "..")
const INIT_DIR = join(REPO_ROOT, "src/cli/cluster/init")
const OUTPUT_PATH = join(INIT_DIR, "tpch.sql")
const GZIP_OUTPUT_PATH = join(INIT_DIR, "tpch.sql.gz")
// Auto-gzip when the dump would be unwieldy in-tree. SF=1 produces ~150MB
// raw / ~30MB gzipped; SF=10 is ~1.5GB raw / ~300MB gzipped. The init
// script already prefers tpch.sql.gz over tpch.sql when both are present.
const SHOULD_GZIP = SF >= 1

const TABLES = [
  "region",
  "nation",
  "supplier",
  "customer",
  "part",
  "partsupp",
  "orders",
  "lineitem",
] as const

const PRIMARY_KEYS: Record<(typeof TABLES)[number], string> = {
  region: "r_regionkey",
  nation: "n_nationkey",
  supplier: "s_suppkey",
  customer: "c_custkey",
  part: "p_partkey",
  partsupp: "ps_partkey, ps_suppkey",
  orders: "o_orderkey",
  lineitem: "l_orderkey, l_linenumber",
}

const tmp = mkdtempSync(join(tmpdir(), "fr-tpch-"))
const exportDir = join(tmp, "export")

console.log(`Generating TPC-H at SF=${SF} via DuckDB...`)
console.log(`  Temp dir: ${tmp}`)

try {
  execSync(
    `duckdb -c "
INSTALL tpch;
LOAD tpch;
CALL dbgen(sf=${SF});
EXPORT DATABASE '${exportDir}' (FORMAT CSV, DELIMITER '|');
"`,
    { stdio: "inherit" },
  )

  // ── Build the unified tpch.sql ───────────────────────────────────
  const lines: string[] = []
  lines.push(
    "-- TPC-H seed database for Postgres CDC demos.",
    `-- Generated by scripts/generate-tpch.ts at SF=${SF}.`,
    "-- Regenerate with `pnpm tpch:gen`. Do not edit by hand.",
    "--",
    "-- Consumed by `00-init-databases.sh` and the pg-init Job's `pg-seed.sh`.",
    "",
    "BEGIN;",
    "",
    "-- Bulk-load tuning. SET LOCAL is scoped to the enclosing transaction",
    "-- so settings revert on COMMIT — safe under psql --single-transaction",
    "-- and under the Docker entrypoint's temp-server load.",
    "SET LOCAL maintenance_work_mem = '1GB';",
    "SET LOCAL synchronous_commit = OFF;",
    "SET LOCAL session_replication_role = 'replica';",
    "",
  )

  // Schema DDL (DuckDB types are Postgres-compatible — BIGINT, INTEGER,
  // VARCHAR, DECIMAL, DATE all map 1:1).
  const rawSchema = readFileSync(join(exportDir, "schema.sql"), "utf-8")
  lines.push(
    "-- ── Tables ───────────────────────────────────────────────────────",
  )
  // DuckDB writes ";;" separators; collapse to single ";", split per
  // statement, strip trailing semicolons (the last statement has no
  // newline so the split keeps its `;`), then re-add a single `;`.
  const ddl = rawSchema.replace(/;;/g, ";").trim()
  for (const stmt of ddl.split(/;\s*\n/).filter(Boolean)) {
    const cleaned = stmt.trim().replace(/;+$/, "")
    lines.push(`${cleaned};`)
  }
  lines.push("")

  // Inline data via \COPY ... FROM STDIN.
  for (const table of TABLES) {
    const csvPath = join(exportDir, `${table}.csv`)
    if (!existsSync(csvPath)) continue
    const csv = readFileSync(csvPath, "utf-8").trimEnd()
    const rowCount = csv.split("\n").length
    lines.push(
      `-- ── ${table} (${rowCount.toLocaleString()} rows) ─────────────────────`,
    )
    lines.push(
      `COPY ${table} FROM STDIN WITH (FORMAT csv, DELIMITER '|');`,
      csv,
      "\\.",
      "",
    )
  }

  // Primary keys after data — load is faster without index maintenance.
  lines.push(
    "-- ── Primary keys ─────────────────────────────────────────────────",
  )
  for (const table of TABLES) {
    lines.push(`ALTER TABLE ${table} ADD PRIMARY KEY (${PRIMARY_KEYS[table]});`)
  }
  lines.push("")
  lines.push("COMMIT;")
  lines.push("")

  const dump = lines.join("\n")
  const rawSizeMB = (Buffer.byteLength(dump) / 1024 / 1024).toFixed(2)

  if (SHOULD_GZIP) {
    // Auto-gzip at SF >= 1: the raw dump is too unwieldy to keep on disk
    // uncompressed, and we don't want both `tpch.sql` (committed,
    // SF=0.01) and a stale `tpch.sql` (local, SF=N) competing for the
    // same path. The init script already prefers .gz when present.
    const gz = gzipSync(dump, { level: 6 })
    writeFileSync(GZIP_OUTPUT_PATH, gz)
    if (existsSync(OUTPUT_PATH)) {
      // Avoid leaving a stale uncompressed dump alongside the new gz —
      // 00-init-databases.sh prefers .gz, but a leftover .sql confuses
      // anyone inspecting the init dir.
      const committedSize = readFileSync(OUTPUT_PATH).length
      // Keep the committed SF=0.01 dump (tiny, ~10MB) untouched.
      if (committedSize > 25 * 1024 * 1024) unlinkSync(OUTPUT_PATH)
    }
    const gzSizeMB = (gz.byteLength / 1024 / 1024).toFixed(2)
    console.log(
      `\nWrote ${GZIP_OUTPUT_PATH} (${gzSizeMB} MB compressed, ${rawSizeMB} MB raw)`,
    )
  } else {
    writeFileSync(OUTPUT_PATH, dump)
    console.log(`\nWrote ${OUTPUT_PATH} (${rawSizeMB} MB)`)
  }
} finally {
  rmSync(tmp, { recursive: true, force: true })
}
