#!/usr/bin/env tsx
/**
 * Generates a PostgreSQL-compatible TPC-H seed dump using DuckDB's
 * tpch extension, writing to `src/cli/cluster/init/tpch.sql`.
 *
 * The dump is consumed by:
 *   • Docker lane: `00-init-databases.sh` runs psql -f tpch.sql at first
 *     boot of the bundled timescaledb container.
 *   • Minikube lane: `Dockerfile.pg-init` COPYs tpch.sql into /data/, the
 *     pg-init Job's `pg-seed.sh` then loads it.
 *
 * Usage:
 *   pnpm tpch:gen                    # SF=0.01 (default — keeps repo lean)
 *   TPCH_SF=0.1 pnpm tpch:gen        # full proposal scale (commits gzipped)
 *   TPCH_SF=0.001 pnpm tpch:gen      # tiny — useful for CI snapshots
 *
 * Requirements:
 *   • DuckDB CLI on PATH (brew install duckdb)
 *   • The tpch extension auto-installs on first invocation.
 */

import { execSync } from "node:child_process"
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"

const SF = Number.parseFloat(process.env.TPCH_SF ?? "0.01")
const REPO_ROOT = join(import.meta.dirname, "..")
const OUTPUT_PATH = join(REPO_ROOT, "src/cli/cluster/init/tpch.sql")

const TABLES = [
  "region",
  "nation",
  "supplier",
  "customer",
  "part",
  "partsupp",
  "orders",
  "lineitem",
] as const

const PRIMARY_KEYS: Record<(typeof TABLES)[number], string> = {
  region: "r_regionkey",
  nation: "n_nationkey",
  supplier: "s_suppkey",
  customer: "c_custkey",
  part: "p_partkey",
  partsupp: "ps_partkey, ps_suppkey",
  orders: "o_orderkey",
  lineitem: "l_orderkey, l_linenumber",
}

const tmp = mkdtempSync(join(tmpdir(), "fr-tpch-"))
const exportDir = join(tmp, "export")

console.log(`Generating TPC-H at SF=${SF} via DuckDB...`)
console.log(`  Temp dir: ${tmp}`)

try {
  execSync(
    `duckdb -c "
INSTALL tpch;
LOAD tpch;
CALL dbgen(sf=${SF});
EXPORT DATABASE '${exportDir}' (FORMAT CSV, DELIMITER '|');
"`,
    { stdio: "inherit" },
  )

  // ── Build the unified tpch.sql ───────────────────────────────────
  const lines: string[] = []
  lines.push(
    "-- TPC-H seed database for Postgres CDC demos.",
    `-- Generated by scripts/generate-tpch.ts at SF=${SF}.`,
    "-- Regenerate with `pnpm tpch:gen`. Do not edit by hand.",
    "--",
    "-- Consumed by `00-init-databases.sh` and the pg-init Job's `pg-seed.sh`.",
    "",
    "BEGIN;",
    "",
  )

  // Schema DDL (DuckDB types are Postgres-compatible — BIGINT, INTEGER,
  // VARCHAR, DECIMAL, DATE all map 1:1).
  const rawSchema = readFileSync(join(exportDir, "schema.sql"), "utf-8")
  lines.push(
    "-- ── Tables ───────────────────────────────────────────────────────",
  )
  // DuckDB writes ";;" separators; collapse to single ";", split per
  // statement, strip trailing semicolons (the last statement has no
  // newline so the split keeps its `;`), then re-add a single `;`.
  const ddl = rawSchema.replace(/;;/g, ";").trim()
  for (const stmt of ddl.split(/;\s*\n/).filter(Boolean)) {
    const cleaned = stmt.trim().replace(/;+$/, "")
    lines.push(`${cleaned};`)
  }
  lines.push("")

  // Inline data via \COPY ... FROM STDIN.
  for (const table of TABLES) {
    const csvPath = join(exportDir, `${table}.csv`)
    if (!existsSync(csvPath)) continue
    const csv = readFileSync(csvPath, "utf-8").trimEnd()
    const rowCount = csv.split("\n").length
    lines.push(
      `-- ── ${table} (${rowCount.toLocaleString()} rows) ─────────────────────`,
    )
    lines.push(
      `COPY ${table} FROM STDIN WITH (FORMAT csv, DELIMITER '|');`,
      csv,
      "\\.",
      "",
    )
  }

  // Primary keys after data — load is faster without index maintenance.
  lines.push(
    "-- ── Primary keys ─────────────────────────────────────────────────",
  )
  for (const table of TABLES) {
    lines.push(`ALTER TABLE ${table} ADD PRIMARY KEY (${PRIMARY_KEYS[table]});`)
  }
  lines.push("")
  lines.push("COMMIT;")
  lines.push("")

  const dump = lines.join("\n")
  writeFileSync(OUTPUT_PATH, dump)
  const sizeMB = (Buffer.byteLength(dump) / 1024 / 1024).toFixed(2)
  console.log(`\nWrote ${OUTPUT_PATH} (${sizeMB} MB)`)

  if (Number.parseFloat(sizeMB) > 50) {
    console.log(
      "  Dump exceeds 50MB — consider committing gzipped (rename .sql → .sql.gz, gzip it).",
    )
  }
} finally {
  rmSync(tmp, { recursive: true, force: true })
}
