FROM flink:2.0.1

# Download Kafka SQL connector JAR for Flink 2.0.1
RUN wget -q -P /opt/flink/lib/ \
  https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.1-2.0/flink-sql-connector-kafka-4.0.1-2.0.jar

# Download JDBC connector + PostgreSQL driver for Flink 2.0.1
RUN wget -q -P /opt/flink/lib/ \
  https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-1.19/flink-connector-jdbc-3.2.0-1.19.jar \
  && wget -q -P /opt/flink/lib/ \
  https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.4/postgresql-42.7.4.jar
